#!/bin/bash
#
# Finds the package that owns a file.
#

if command -v dpkg >/dev/null 2>&1; then
	dpkg -S $*
elif command -v rpm >/dev/null 2>&1; then
	rpm --query --file $*
else
	echo "No package manager found."
fi
