#!/bin/sh
#
# Lists the contents of an installed package.
#

if command -v dpkg >/dev/null 2>&1; then
	dpkg -L $*
elif command -v rpm >/dev/null 2>&1; then
	rpm --query --list $*
else
	echo "No package manager found."
fi
