#!/bin/sh
#
# Searches installed package names.
#

if command -v dpkg >/dev/null 2>&1; then
	dpkg --get-selections | grep $*
elif command -v rpm >/dev/null 2>&1; then
	rpm --query --all | grep $*
else
	echo "No package manager found."
fi
