#!/bin/sh
#
# Queries information of an installed package.
#

if command -v dpkg >/dev/null 2>&1; then
	dpkg -s $*
elif command -v rpm >/dev/null 2>&1; then
	rpm --query -i $*
else
	echo "No package manager found."
fi
