#!/bin/sh
#
# Queries information of an installed package.
#

if command -v pkcon >/dev/null 2>&1; then
	pkcon remove $*
elif command -v apt-get >/dev/null 2>&1; then
	apt-get --purge autoremove $*
elif command -v dpkg >/dev/null 2>&1; then
	dpkg --purge $*
elif command -v rpm >/dev/null 2>&1; then
	rpm --erase $*
else
	echo "No package manager found."
fi
