#!/bin/sh
#
# Lists the contents of a package file.
#

if command -v dpkg >/dev/null 2>&1; then
	dpkg -c $*
elif command -v rpm >/dev/null 2>&1; then
	rpm --query --list --package $*
else
	echo "No package manager found."
fi


