#!/bin/sh
#
# Installs a package file.
#

if command -v dpkg >/dev/null 2>&1; then
	dpkg -i $*
elif command -v rpm >/dev/null 2>&1; then
	rpm --upgrade -v --hash $*
else
	echo "No package manager found."
fi
